-- MySQL Script generated by MySQL Workbench
-- Thu 02 Nov 2017 10:32:07 PM BRST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema andrealissonrodrigo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema andrealissonrodrigo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `andrealissonrodrigo` DEFAULT CHARACTER SET utf8 ;
USE `andrealissonrodrigo` ;

-- -----------------------------------------------------
-- Table `andrealissonrodrigo`.`respostas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `andrealissonrodrigo`.`respostas` ;

CREATE TABLE IF NOT EXISTS `andrealissonrodrigo`.`respostas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- comidas --

INSERT INTO `andrealissonrodrigo`.`respostas` (`nome`, `tipo`) VALUES ('macarrao', 'comida');
INSERT INTO `andrealissonrodrigo`.`respostas` (`nome`, `tipo`) VALUES ('bolacha', 'comida');
INSERT INTO `andrealissonrodrigo`.`respostas` (`nome`, `tipo`) VALUES ('batata', 'comida');
INSERT INTO `andrealissonrodrigo`.`respostas` (`nome`, `tipo`) VALUES ('amora', 'comida');
INSERT INTO `andrealissonrodrigo`.`respostas` (`nome`, `tipo`) VALUES ('caramelo', 'comida');
INSERT INTO `andrealissonrodrigo`.`respostas` (`nome`, `tipo`) VALUES ('damasco', 'comida');
INSERT INTO `andrealissonrodrigo`.`respostas` (`nome`, `tipo`) VALUES ('espinafre', 'comida');
INSERT INTO `andrealissonrodrigo`.`respostas` (`nome`, `tipo`) VALUES ('figo', 'comida');
INSERT INTO `andrealissonrodrigo`.`respostas` (`nome`, `tipo`) VALUES ('goiaba', 'comida');
INSERT INTO `andrealissonrodrigo`.`respostas` (`nome`, `tipo`) VALUES ('hibisco', 'comida');
INSERT INTO `andrealissonrodrigo`.`respostas` (`nome`, `tipo`) VALUES ('iogurte', 'comida');
INSERT INTO `andrealissonrodrigo`.`respostas` (`nome`, `tipo`) VALUES ('jaca', 'comida');
